name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: v18.x
          registry-url: https://registry.npmjs.org/
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Publish package on NPM 📦
        run: |
          deno task dnt
          npm install -g @jsdevtools/npm-publish
          npm-publish --token=${{ secrets.NPM_TOKEN }} --access public ./npm/package.json
